"""English word set — ported from archive/lswitch/dictionary.py."""

ENGLISH_WORDS: set[str] = {
    'a', 'an', 'the', 'and', 'or', 'but', 'if', 'then', 'else', 'when', 'at', 'by', 'for', 'from',
    'in', 'on', 'to', 'with', 'of', 'as', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
    'my', 'your', 'his', 'its', 'our', 'their', 'mine', 'yours', 'hers', 'ours', 'theirs',
    'this', 'that', 'these', 'those', 'who', 'what', 'where', 'why', 'how', 'which',
    'all', 'some', 'any', 'many', 'much', 'few', 'little', 'more', 'most', 'other', 'another',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'first', 'second',
    'no', 'not', 'yes', 'can', 'could', 'will', 'would', 'shall', 'should', 'may', 'might', 'must',
    'do', 'does', 'did', 'done', 'doing', 'have', 'has', 'had', 'having', 'get', 'got', 'getting',
    'make', 'made', 'making', 'go', 'went', 'gone', 'going', 'come', 'came', 'coming', 'see', 'saw',
    'seen', 'seeing', 'know', 'knew', 'known', 'knowing', 'think', 'thought', 'thinking', 'take',
    'took', 'taken', 'taking', 'want', 'wanted', 'wanting', 'give', 'gave', 'given', 'giving',
    'use', 'used', 'using', 'find', 'found', 'finding', 'tell', 'told', 'telling', 'ask', 'asked',
    'work', 'worked', 'working', 'call', 'called', 'calling', 'try', 'tried', 'trying', 'need',
    'feel', 'felt', 'feeling', 'become', 'became', 'becoming', 'leave', 'left', 'leaving', 'put',
    'mean', 'meant', 'meaning', 'keep', 'kept', 'keeping', 'let', 'begin', 'began', 'beginning',
    'seem', 'seemed', 'seeming', 'help', 'helped', 'helping', 'show', 'showed', 'showing', 'hear',
    'heard', 'hearing', 'play', 'played', 'playing', 'run', 'ran', 'running', 'move', 'moved',
    'live', 'lived', 'living', 'believe', 'believed', 'believing', 'bring', 'brought', 'bringing',
    'happen', 'happened', 'happening', 'write', 'wrote', 'written', 'writing', 'sit', 'sat',
    'stand', 'stood', 'standing', 'lose', 'lost', 'losing', 'pay', 'paid', 'paying', 'meet', 'met',
    'include', 'included', 'including', 'continue', 'continued', 'continuing', 'set', 'learn',
    'change', 'changed', 'changing', 'lead', 'led', 'leading', 'understand', 'understood',
    'watch', 'watched', 'watching', 'follow', 'followed', 'following', 'stop', 'stopped', 'stopping',
    'create', 'created', 'creating', 'speak', 'spoke', 'spoken', 'speaking', 'read', 'reading',
    'allow', 'allowed', 'allowing', 'add', 'added', 'adding', 'spend', 'spent', 'spending', 'grow',
    'open', 'opened', 'opening', 'walk', 'walked', 'walking', 'win', 'won', 'winning', 'offer',
    'remember', 'remembered', 'remembering', 'love', 'loved', 'loving', 'consider', 'considered',
    'appear', 'appeared', 'appearing', 'buy', 'bought', 'buying', 'wait', 'waited', 'waiting',
    'serve', 'served', 'serving', 'die', 'died', 'dying', 'send', 'sent', 'sending', 'expect',
    'build', 'built', 'building', 'stay', 'stayed', 'staying', 'fall', 'fell', 'fallen', 'falling',
    'cut', 'cutting', 'reach', 'reached', 'reaching', 'kill', 'killed', 'killing', 'raise', 'raised',
    'pass', 'passed', 'passing', 'sell', 'sold', 'selling', 'require', 'required', 'requiring',
    'report', 'reported', 'reporting', 'decide', 'decided', 'deciding', 'pull', 'pulled', 'pulling',
    'time', 'year', 'day', 'week', 'month', 'hour', 'minute', 'second', 'morning', 'afternoon',
    'evening', 'night', 'today', 'yesterday', 'tomorrow', 'monday', 'tuesday', 'wednesday',
    'thursday', 'friday', 'saturday', 'sunday', 'january', 'february', 'march', 'april',
    'june', 'july', 'august', 'september', 'october', 'november', 'december', 'spring', 'summer',
    'autumn', 'winter', 'season', 'century', 'period', 'moment', 'history', 'future', 'past',
    'people', 'person', 'man', 'woman', 'child', 'boy', 'girl', 'friend', 'family', 'mother',
    'father', 'parent', 'son', 'daughter', 'brother', 'sister', 'husband', 'wife', 'baby', 'kid',
    'way', 'place', 'world', 'country', 'city', 'town', 'area', 'home', 'house', 'room', 'street',
    'door', 'window', 'floor', 'wall', 'table', 'chair', 'bed', 'school', 'office', 'court', 'church',
    'thing', 'fact', 'case', 'problem', 'issue', 'question', 'answer', 'reason', 'result',
    'end', 'point', 'group', 'number', 'part', 'system', 'order', 'form', 'line', 'side', 'level',
    'hand', 'eye', 'head', 'face', 'body', 'heart', 'mind', 'voice', 'foot', 'back', 'arm', 'leg',
    'name', 'word', 'language', 'book', 'letter', 'page', 'story', 'idea', 'information', 'news',
    'money', 'power', 'law', 'right', 'left', 'state', 'government', 'company', 'business', 'service',
    'water', 'food', 'air', 'fire', 'light', 'sound', 'color', 'red', 'blue', 'green', 'white',
    'black', 'car', 'road', 'tree', 'land', 'war', 'game', 'music', 'art', 'program', 'computer',
    'phone', 'internet', 'email', 'website', 'file', 'data', 'image', 'video', 'picture', 'photo',
    'good', 'bad', 'new', 'old', 'great', 'big', 'small', 'long', 'short', 'high', 'low',
    'young', 'early', 'late', 'important', 'different', 'same', 'large', 'social', 'national', 'own',
    'other', 'wrong', 'true', 'false', 'real', 'full', 'sure', 'clear', 'hard', 'easy',
    'strong', 'free', 'happy', 'sorry', 'ready', 'simple', 'certain', 'personal',
    'best', 'better', 'worse', 'worst', 'main', 'only', 'public', 'able', 'possible', 'local',
    'hello', 'hi', 'bye', 'goodbye', 'thanks', 'please', 'welcome', 'okay', 'ok', 'well',
}
